[package]
name = "index"
version = "2.0.0"
authors = [
  "Cristian Enguídanos Nebot <53697395+cenguidanos@users.noreply.github.com>"
]
edition = "2018"

[dependencies]
http = "0.2"
now_lambda = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
