[package]
name = "random"
version = "0.1.0"
authors = [
  "Cristian Enguídanos Nebot <53697395+cenguidanos@users.noreply.github.com>"
]
edition = "2018"

[dependencies]
now_lambda = "*"
rand = "0.8.3"

[lib]
name = "util"
path = "_lib/util.rs"
